name: virtual_waiter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.3+1
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.1
  intl: ^0.17.0
  obs: ^0.0.4
  cached_network_image: ^3.3.1
  reward_popup: ^0.0.7
  uuid: ^4.4.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  animated_text_kit: ^4.2.2
  get: ^4.6.6


flutter:
  assets:
    - images/

  uses-material-design: true

  fonts:
    - family: Saira
      fonts:
        - asset: fonts/Saira-SemiBold.ttf
          style: italic
    - family: Balow
      fonts:
        - asset: fonts/Barlow-Regular.ttf
        - asset: fonts/Barlow-Light.ttf
        - asset: fonts/Barlow-Medium.ttf
        - asset: fonts/Barlow-SemiBold.ttf
