import '../model/MenuItem.dart';

final List<MenuItem> kMenuItemList = [
  MenuItem(
    id: 1,
    name: 'Spring Rolls',
    category: 'Cold Dishes',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2500.0,
    availableQuantity: 15,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 1,
    name: 'Spring Rolls',
    category: 'Appetizer',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2500.0,
    availableQuantity: 15,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 1,
    name: 'Spring Rolls',
    category: 'Cold Dishes',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2500.0,
    availableQuantity: 15,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 1,
    name: 'Spring Rolls',
    category: 'Cold Dishes',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2500.0,
    availableQuantity: 15,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 1,
    name: 'Spring Rolls',
    category: 'Cold Dishes',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2500.0,
    availableQuantity: 0,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 1,
    name: 'Spring Rolls',
    category: 'Cold Dishes',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2500.0,
    availableQuantity: 1,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 2,
    name: 'Grilled Chicken Breast',
    category: 'Hot Dishes',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 3250.0,
    availableQuantity: 12,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 3,
    name: 'Tomato Basil Soup',
    category: 'Soup',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 1350.0,
    availableQuantity: 18,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 4,
    name: 'Caesar Salad',
    category: 'Cold Dishes',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 1800.0,
    availableQuantity: 10,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 5,
    name: 'BBQ Ribs',
    category: 'Grill',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2900.0,
    availableQuantity: 8,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 6,
    name: 'Chocolate Lava Cake',
    category: 'Dessert',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 1500.0,
    availableQuantity: 20,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 7,
    name: 'Spicy Tuna Roll',
    category: 'Cold Dishes',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2200.0,
    availableQuantity: 12,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 8,
    name: 'Lobster Bisque',
    category: 'Soup',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 2700.0,
    availableQuantity: 6,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 9,
    name: 'Garlic Breadsticks',
    category: 'Appetizer',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 500.0,
    availableQuantity: 18,
    tags: ['Vegan', 'Vegetarian'],
  ),
  MenuItem(
    id: 10,
    name: 'Ice Cream Sundae',
    category: 'Dessert',
    imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Vegetable-Spring-Rolls-3.jpg',
    price: 1100.0,
    availableQuantity: 25,
    tags: ['Vegan', 'Vegetarian'],
  ),
];
